### PR TITLE
Fixes issue #51.

### PR DESCRIPTION
**Pull request by blernermhc**
Fixes the NumberFormat problem seen in the international case.

### CODE REVIEW

**Comment by tfjmp** [comment]
Hi Barbara, can you `git pull origin fix` in your branch and fix the conflicts?

**Comment by tfjmp** [comment]
The last commit seems to introduce a regression in `src/laser/ddg/search/SearchIndex.java`; please also check `src/laser/ddg/visualizer/PrefuseGraphBuilder.java`.

**Comment by blernermhc** [comment]
What is the nature of the regression problem you are seeing?  Are you referring to the commit from this morning or from yesterday?

**Comment by tfjmp** [comment]
3e35a5a2c0faabbc75f75a9c9343aa6767e8b249 << in `src/laser/ddg/search/SearchIndex.java` <> operators have been replaced back. The rest seems ok.

**Comment by blernermhc** [comment]
Ok, check this one.

**Pull request merged**
