### PR TITLE
Sourced scripts

### PR DESCRIPTION
**Pull request by blernermhc**
This branch adds the ability to manage a script that sources other scripts.  The user can view any of the scripts with the Show R Script menu command.  The user can also view the code from any of the scripts by right-clicking on a node and selecting Show Code.

Right-clicking on a data node that represents a function definition has also been updated to use the same mechanism to show the code.

### CODE REVIEW

**Comment by MKLau** [comment]
Sounds cool!

**Comment by tfjmp** [comment]
Hi Barbara, can you `git pull origin development` in your branch and fix the conflicts?

**Comment by tfjmp** [comment]
Would not it be better to store timestamp as a `Date` (or other class representing time) rather than as a String? If so only converting the data to a string where needed.

**Comment by blernermhc** [comment]
I assume you are referring to the timestamps associated with sourced scripts.  We only use these timestamps to generate filenames for where we store files when they are saved to the database.  I don't think we do any time-based calculations.  Is there some place you see where it would be useful to have them as Dates?

**Comment by tfjmp** [comment]
Not at the moment, but that would avoid bug in the future where data are being translated back and forth. I could easily imagine that someone may at some point used an attribute named timestamp to do timestamp related things.

**Comment by blernermhc** [comment]
I would prefer waiting until there is a need for a Date.  Currently, we have a need for a String, so if we store it as a Date in memory, we are going to need to convert it back to a String anyway.

**Pull request merged**
